### ISSUE TITLE
typings specify properties documented as having defaults as required

### ISSUE THREAD

**Issue by rovrevik** [plopjs/node-plop#134]
Several properties in the ActionType(s) hierarchy should be declared as `property?` I think.
comparing: https://github.com/plopjs/node-plop/blob/master/index.d.ts#L65
to: https://github.com/plopjs/plop#your-first-plopfile

**Comment by rovrevik** [comment]
Looks like this might be addressed by: https://github.com/plopjs/node-plop/pull/132

**Comment by crutchcorn** [comment]
I think you're right, I think we can safely close this issue
