### ISSUE TITLE
Latest version of node-plop gives strange errors in react application

### ISSUE THREAD

**Issue by sarita-kumari-dev** [plopjs/node-plop#138]
Hi was having node-plop version 0.16.0 in my application.
During App scan I found some issues of security vulnerabilities which were related to handlebars packages. Since the parent of handlebars was node-plop hence I tried to update node-plop package to the latest 0.23.0 and then started to get some issues - 

Error: ENOENT: no such file or directory, open 'D:\home\vcap\app\server\certs\IBMid\blueid-server.crt'
    at Object.openSync (fs.js:443:3)

There is no path which is specified above.
Kindly look into it and send updates on the same.

**Comment by amwmedia** [comment]
are you using node-plop directly? or is it in your project because it was added by `plop`?

**Comment by Sarita-persi** [comment]
It is being used directly in package.json and in package-lock.json it is present as parent of handlerbars package.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by crutchcorn** [comment]
Closing this due to age and also because we are moving all of our issues to the updated plop monorepo which now holds `node-plop`:

https://github.com/plopjs/plop/
