### ISSUE TITLE
action.data function arguments

### ISSUE THREAD

**Issue by jacksteamdev** [plopjs/node-plop#142]
It seems that when `action.data` is a function, it receives no arguments.

https://github.com/plopjs/node-plop/blob/decdd3f32ecdac65069feeafb07ee8e3ba37be79/src/generator-runner.js#L114-L116

I found the type definition ~~confusing~~ misleading:

https://github.com/plopjs/node-plop/blob/decdd3f32ecdac65069feeafb07ee8e3ba37be79/index.d.ts#L171-L176

Should the data function receive the existing data from the prompts? This could be useful for file loading, etc...

I can make a pull request if this is welcome!

**Comment by armand1m** [comment]
Hey! I just got this fixed on #165

**Comment by ThisIsMissEm** [comment]
@armand1m I don't think #165 strictly fixes this, I'm currently trying to do something where I provide an additional object of data to the template I'm rendering based on the users' answers, and this seems to not be a thing that's possible, which is what I think @jacksteamdev was trying to get at.

**Comment by amwmedia** [comment]
@ThisIsMissEm you are correct, the PR referenced doesn't add this specific feature. However, in the interim, you could accomplish what you are looking to do with a [CustomActionFunction](https://plopjs.com/documentation/#custom-action-function-) that executes before the action that needs the data you are trying to provide to the template. A custom action function has access to the answer data (first parameter) and it can mutate the answer object, passing new or changed data forward to all consecutive actions. cc @jacksteamdev

**Comment by armand1m** [comment]
@ThisIsMissEm Indeed I got it wrong, my bad. The PR referenced is focused on fixing the type definitions inconsistencies instead.

**Comment by ThisIsMissEm** [comment]
I ended up doing the CustomActionFunction approach, but it certainly wasn't my first guess. Perhaps it's something either for documentation or we allow the data function to receive answers & potentially be async? Or both?
