### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by zonzujiro** [plopjs/node-plop#146]
Not sure, that this is an *issue*, this is an OSS and I don't want to be pushy, but can you make a release? :) Please 😄

Last release was in November and right now using of `plop` in TS is blocked by:

1. https://github.com/plopjs/node-plop/commit/f99584def57e4d87494c757badabff6fdf9a39e8 - missing types for `DynamicActionFunction`, which was added in December
2. https://github.com/plopjs/node-plop/pull/145 and missing support of ESM modules.

https://github.com/plopjs/node-plop/compare/v0.23.0...master list of comments with diff

Much thx for your job on this generator! 👍

**Comment by crutchcorn** [comment]
New release has been cut under `0.24.0`:

https://github.com/plopjs/node-plop/releases/tag/v0.24.0

Thanks for the reminder and apologies for taking so long :)

**Comment by zonzujiro** [comment]
No problem. Thank you for quick response!
