### ISSUE TITLE
A way to perform final code transformations

### ISSUE THREAD

**Issue by jacksteamdev** [plopjs/node-plop#154]
I've been adding Plop to my projects over the last few months, and something I've been wanting is an easy way to transform the template output before writing the file. Oftentimes it would be easier/faster to drop some code into the action, rather than abandon the default actions to write a Custom Action Function or a new action. 

Use cases include linting and formatting, or making a one-off change instead of creating and loading a new Handlebars helper.

I found one issue that might relate to this: https://github.com/plopjs/plop/issues/80

One way to accomplish this would be to add an optional `transform()` function to the actions `add`, `addMany`, and `modify`. It would take the template output and the Inquirer data, and should return or resolve the final file contents as a string.

```typescript
function transform(templateOutput: string, data: any): string | Promise<string>
```

A quick look suggests it would be trivial to implement.

https://github.com/plopjs/node-plop/blob/7b53773310d9d9381210bc827a194c2b77e5e820/src/actions/_common-action-add-file.js#L36-L42

I've got some OSS time this week, so if there's no objections I can put together a pull request.

**Comment by crutchcorn** [comment]
I think this feature would need further documentation (especially alongside an implementation) and some tests alongside them, but I'm personally not against the idea! I think it would be a welcome contribution :)

**Comment by jacksteamdev** [comment]
Great! Should I do separate PRs for each action, or all in one? What would be easier for you to review?

**Comment by crutchcorn** [comment]
I think if they're seperate commits but on the same PR it should be fine (and provide a cleaner diff for me to dive into)

**Comment by jacksteamdev** [comment]
@crutchcorn I was looking at how to update the docs. It looks like I update the readme on the main repo and that will propagate over to the website. Is this correct?

**Comment by crutchcorn** [comment]
I believe that is correct, yes.
