### ISSUE TITLE
No typing for functional prompts in generators

### ISSUE THREAD

**Issue by lbneff** [plopjs/node-plop#162]
Hello, I've been using the library and found a slight issue with the typing for generators. 

There appears to be support for the prompt value of a generator config to be a function: 		
https://github.com/plopjs/node-plop/blob/74f4e08dc44e81945ec4a4f74847bb2319c26436/src/generator-runner.js#L19

But this is not reflected in the typing:
```
  prompts: inquirer.Question[];
```
Let me know if you'd like me to take a crack at this! Should be simple and very similar to the actions typing in that same interface:
```
  actions: Actions | DynamicActionFunction;
``` 

Thanks!

**Comment by armand1m** [comment]
Just fixed this one https://github.com/plopjs/node-plop/pull/165

**Comment by lbneff** [comment]
Thanks for the update!
