### ISSUE TITLE
More actions?

### ISSUE THREAD

**Issue by daniel-ac-martin** [plopjs/node-plop#171]
I'm finding that the included actions are insufficient for what I'm trying to achieve. In addition to rendering templates and modifying files I would like to do the following:
1. Copy files (without worrying about templates and having to escape handlesbars syntax)
2. Symlink files (as there are times where I want to ensure that files stay in sync)

Are these features that you would consider adding at some point?

**Comment by crutchcorn** [comment]
If these actions were added, they likely would be provided by a third-party `plop-pack` that provides a custom action:

https://plopjs.com/documentation/#custom-action-function-

Handled by `plop.load`:

https://github.com/plopjs/plop/blob/master/plop-load.md

If you do end up finding (or building) a `plop-pack` package, be sure to include it in our list of `plop-packs`:

https://github.com/plopjs/awesome-plop

**Comment by daniel-ac-martin** [comment]
@crutchcorn: Thanks for the information. That makes things far more clear. I'll probably publish something once I've cleaned up the code a bit.

**Comment by crutchcorn** [comment]
@daniel-ac-martin - did you end up making a package for this? Would you be willing to share it with us? :D Maybe we could add it to awesome-plop?

**Comment by crutchcorn** [comment]
Re-opening until we have a known `plop-pack` with these functionalities

**Comment by daniel-ac-martin** [comment]
@crutchcorn: I've written something but I've not packaged them up and published them yet.

I'll post here when I do.

**Comment by amwmedia** [comment]
If you need some direction, there's now a video tutorial that outlines the process. 👍 
https://www.youtube.com/watch?v=pe0lwYSvXeI

**Comment by daniel-ac-martin** [comment]
FYI, I've now published some stuff: https://www.npmjs.com/package/@not-govuk/plop-pack

But it's jumbled up together and it needs some documentation writing before it's much use to people. You can get a fell what's included here though: https://github.com/daniel-ac-martin/NotGovUK/tree/master/lib/plop-pack/src/actions

I'll comment again when it's in better shape. Thanks for the tips on how to do this.

**Comment by amwmedia** [comment]
These look awesome! When they are ready, make sure you submit a PR to awesome-plop so the community can find them.
