### ISSUE TITLE
Release w new version with latest changes

### ISSUE THREAD

**Issue by feimosi** [plopjs/node-plop#175]
Namely, the following change hasn't been release yet: https://github.com/plopjs/node-plop/pull/170
i.e. v0.26.0 doesn't include it, while the package `plop` relies on this change:
https://github.com/plopjs/plop/blob/master/src/plop.d.ts

It all results in typing errors:
![image](https://user-images.githubusercontent.com/5721520/85582419-b68a5200-b63d-11ea-8fd0-373f5fc10d4a.png)

**Comment by amwmedia** [comment]
Looks like this was just release. Thanks @crutchcorn!
