### ISSUE TITLE
Ability to disable html escaping on templateFiles

### ISSUE THREAD

**Issue by ThisIsMissEm** [plopjs/node-plop#181]
For some template files, e.g., `.md` and `.tsx`/`.jsx`, it is safe to output strings that don't have HTML escaping, as these languages don't need it.

Proposal:
- add a `escapeHtml` option to all methods that take a `templateFile`
- provide `htmlSafe` and `escapeHtml` helper methods
- potentially automatically detect if a file is `.md.hbs` or `.tsx.hbs`/`.jsx.hbs`, and automatically set `escapeHtml` to false as a sensible default

Usage:

In the `actions` array:
```
      {
        type: 'add',
        path: 'src/features/{{kebabCase name}}/README.md',
        templateFile: 'templates/feature-readme.md.hbs',
        escapeHtml: false,
      },
```

Then in `'templates/feature-readme.md.hbs',` if I wish to escape something, I can with `{{escapeHtml str}}`

**Comment by amwmedia** [comment]
I'm not sure I understand the core issue here. What is the problem that html escaping solves within this context?

**Comment by ThisIsMissEm** [comment]
By default Handlerbars escapes all variables in templates, so currently, `Users & Groups` becomes `Users &amp; Groups` in the rendered template, which isn't what you want (most likely), when using `# Team: {{name}}` in a template. To get the desired output, I had to add a `safe` helper to my plopfile: 

```js
  plop.setHelper('safe', function (str) {
    return new Handlebars.SafeString(str);
  });
```

**Comment by ThisIsMissEm** [comment]
(Though I have only just noticed the "triple stash" variable insertion method, which I did not earlier know about)

**Comment by amwmedia** [comment]
Yes, triple braces will be your friend 👍
