### ISSUE TITLE
Check inquirer function expectations

### ISSUE THREAD

**Issue by RobinKnipe** [plopjs/node-plop#189]
https://github.com/plopjs/node-plop/blob/a187e28a5ddc4c6b8e6d9495d95151daf1a2f4c2/src/prompt-bypass.js#L136

The line above (and others in the codebase) don't fully honour the `inquirer` function parameters. Most of the "question" functions have the form `(input, answers) => ...`. See the docs [here](https://github.com/SBoudrias/Inquirer.js#question) for more details.

**Comment by crutchcorn** [comment]
I'm not entirely sure I understand. What does this impact? Could you demonstrate what a "fix" would be?

**Comment by RobinKnipe** [comment]
Fixed by the PR #190 - basically, it just makes sure the `filter` and `validate` functions are called the user's `input` _and_ the hash of the other completed `answers`. This allows filtering and validation to consider _all_ the previously supplied responses as part of their evaluation (not just the response to the current question).
